//
//  PhotoDetailProtocols.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

//MARK: Wireframe -
protocol PhotoDetailWireframeProtocol: class {

    //MARK: - GoBack
    func goBack(nav: UINavigationController?)
}

//MARK: Presenter -
protocol PhotoDetailPresenterProtocol: class {

    //MARK: - GoBack
    func goBack(nav: UINavigationController?)
}

//MARK: Interactor -
protocol PhotoDetailInteractorProtocol: class {
    
    var presenter: PhotoDetailPresenterProtocol?  { get set }
}

//MARK: View -
protocol PhotoDetailViewProtocol: class {
    
    var presenter: PhotoDetailPresenterProtocol?  { get set }
}
