//
//  PhotoDetailPresenter.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class PhotoDetailPresenter: PhotoDetailPresenterProtocol {

    weak private var view: PhotoDetailViewProtocol?
    var interactor: PhotoDetailInteractorProtocol?
    private let router: PhotoDetailWireframeProtocol

    init(interface: PhotoDetailViewProtocol, interactor: PhotoDetailInteractorProtocol?, router: PhotoDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
