//
//  PhotoDetailInteractor.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class PhotoDetailInteractor: PhotoDetailInteractorProtocol {

    weak var presenter: PhotoDetailPresenterProtocol?
}
