//
//  PhotoDetailRouter.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class PhotoDetailRouter: PhotoDetailWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PhotoDetailViewController(nibName: "PhotoDetailViewController", bundle: nil)
        let interactor = PhotoDetailInteractor()
        let router = PhotoDetailRouter()
        let presenter = PhotoDetailPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
