//
//  InitProtocols.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

//MARK: Wireframe -
protocol InitWireframeProtocol: class {

    //MARK: - GoToPhotoList
    func goToPhotoList(nav: UINavigationController?)
    
    //MARK: - GoToAlbumList
    func goToAlbumList(nav: UINavigationController?)
}

//MARK: Presenter -
protocol InitPresenterProtocol: class {

    //MARK: - GoToPhotoList
    func goToPhotoList(nav: UINavigationController?)
    
    //MARK: - GoToAlbumList
    func goToAlbumList(nav: UINavigationController?)
}

//MARK: Interactor -
protocol InitInteractorProtocol: class {
    
    var presenter: InitPresenterProtocol?  { get set }
}

//MARK: View -
protocol InitViewProtocol: class {
    
    var presenter: InitPresenterProtocol?  { get set }
}
