//
//  InitPresenter.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class InitPresenter: InitPresenterProtocol {

    weak private var view: InitViewProtocol?
    var interactor: InitInteractorProtocol?
    private let router: InitWireframeProtocol

    init(interface: InitViewProtocol, interactor: InitInteractorProtocol?, router: InitWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - GoToPhotoList
    func goToPhotoList(nav: UINavigationController?) {
        router.goToPhotoList(nav: nav)
    }
    
    //MARK: - GoToAlbumList
    func goToAlbumList(nav: UINavigationController?) {
        router.goToAlbumList(nav: nav)
    }

}
