//
//  InitViewController.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class InitViewController: UIViewController, InitViewProtocol {

	var presenter: InitPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var containerView: GradientView!
    @IBOutlet weak var photoListView: UIView!
    @IBOutlet weak var albumListView: UIView!
    @IBOutlet weak var headerContainerView: UIView!
    
    //MARK: - Properties
    var gradientView: GradientView!

    //MARK: - Life cycle
	override public func viewDidLoad() {
        super.viewDidLoad()
        
        setUpView()
    }
    
    override public func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        containerView.animateGradient()
    }
    
    //MARK: - Methods
    private func setUpView() {
        headerContainerView.roundCorners(corners: [.layerMinXMaxYCorner, .layerMaxXMaxYCorner], radius: 30.0)
        photoListView.setCorner(cornerRadius: 10.0)
        albumListView.setCorner(cornerRadius: 10.0)
    }
    
    //MARK: - Actions
    @IBAction private func goToPhotoList(_ sender: UIButton) {
        presenter?.goToPhotoList(nav: self.navigationController)
    }
    
    @IBAction private func goToAlbumList(_ sender: UIButton) {
        presenter?.goToAlbumList(nav: self.navigationController)
    }
}
