//
//  InitRouter.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class InitRouter: InitWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = InitViewController(nibName: "InitViewController", bundle: nil)
        let interactor = InitInteractor()
        let router = InitRouter()
        let presenter = InitPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    //MARK: - GoToPhotoList
    func goToPhotoList(nav: UINavigationController?) {
        let view = PhotoListRouter.createModule()
        nav?.pushViewController(view, animated: true)
    }
    
    //MARK: - GoToAlbumList
    func goToAlbumList(nav: UINavigationController?) {
        let view = AlbumListRouter.createModule()
        nav?.pushViewController(view, animated: true)
    }
}
