//
//  AlbumListPresenter.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class AlbumListPresenter: AlbumListPresenterProtocol {

    weak private var view: AlbumListViewProtocol?
    var interactor: AlbumListInteractorProtocol?
    private let router: AlbumListWireframeProtocol

    init(interface: AlbumListViewProtocol, interactor: AlbumListInteractorProtocol?, router: AlbumListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - MakeRequest
    func makeRequest(method: Method) {
        interactor?.makeRequest(method: method)
    }
    
    //MARK: - ReceivedData
    func receivedData(data: Albums) {
        view?.receivedData(data: data)
    }
    
    //MARK: - Error
    func error(message: String) {
        view?.error(message: message)
    }

}
