//
//  AlbumListProtocols.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

//MARK: Wireframe -
protocol AlbumListWireframeProtocol: class {

    //MARK: - GoBack
    func goBack(nav: UINavigationController?)
}

//MARK: Presenter -
protocol AlbumListPresenterProtocol: class {

    //MARK: - MakeRequest
    func makeRequest(method: Method)
    
    //MARK: - ReceivedData
    func receivedData(data: Albums)
    
    //MARK: - Error
    func error(message: String)
    
    //MARK: - GoBack
    func goBack(nav: UINavigationController?)
}

//MARK: Interactor -
protocol AlbumListInteractorProtocol: class {
    
    var presenter: AlbumListPresenterProtocol?  { get set }
    
    //MARK: - MakeRequest
    func makeRequest(method: Method)
}

//MARK: View -
protocol AlbumListViewProtocol: class {
    
    var presenter: AlbumListPresenterProtocol?  { get set }
    
    //MARK: - ReceivedData
    func receivedData(data: Albums)
    
    //MARK: - Error
    func error(message: String)
}
