//
//  PhotoListViewController.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class PhotoListViewController: UIViewController, PhotoListViewProtocol {

	var presenter: PhotoListPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var tableView: UITableView! {
        didSet { tableView.tableFooterView = UIView() }
    }
    
    //MARK: - Properties
    var photos: Photos? {
        didSet { tableView.reloadData() }
    }

    //MARK: - Life cycle
	override public func viewDidLoad() {
        super.viewDidLoad()
        
        setUpView()
        presenter?.makeRequest(method: .photos)
    }
    
    //MARK: - Methods
    private func setUpView() {
        tableView.dataSource = self
        tableView.delegate = self
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 80
        tableView.register(PhotoTVC.nib, forCellReuseIdentifier: PhotoTVC.identifier)
    }

}

//MARK: - PresenterMethods
extension PhotoListViewController {
    func receivedData(data: Photos) {
        photos = data
    }
    
    func error(message: String) {
        print(message)
    }
}

//MARK: - UITableViewDataSource
extension PhotoListViewController: UITableViewDataSource {
    public func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let numberOfRows = photos?.count else { return 0 }
        return numberOfRows
    }
    
    public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: PhotoTVC.identifier, for: indexPath) as! PhotoTVC
        guard let photo = photos?[indexPath.row] else { return UITableViewCell() }
        cell.setModel(photo: photo)
        return cell
    }
}

//MARK: - UITableViewDelegate
extension PhotoListViewController: UITableViewDelegate {
    public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
    }
}
