//
//  PhotoListProtocols.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PhotoListWireframeProtocol: class {

}

//MARK: Presenter -
protocol PhotoListPresenterProtocol: class {

    //MARK: - MakeRequest
    func makeRequest(method: Method)
    
    //MARK: - ReceivedData
    func receivedData(data: Photos)
    
    //MARK: - Error
    func error(message: String)
}

//MARK: Interactor -
protocol PhotoListInteractorProtocol: class {
    
    var presenter: PhotoListPresenterProtocol?  { get set }
    
    //MARK: - MakeRequest
    func makeRequest(method: Method)
}

//MARK: View -
protocol PhotoListViewProtocol: class {
    
    var presenter: PhotoListPresenterProtocol?  { get set }
    
    //MARK: - ReceivedData
    func receivedData(data: Photos)
    
    //MARK: - Error
    func error(message: String)
}
