//
//  PhotoListInteractor.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class PhotoListInteractor: PhotoListInteractorProtocol {
    
    weak var presenter: PhotoListPresenterProtocol?
    
    //MARK: - Properties
    let networkConnection: NetworkConnection = NetworkConnection()
    
    //MARK: - MakeRequest
    func makeRequest(method: Method) {
        networkConnection.delegate = self
        networkConnection.makeRequest(withMethod: method, dataType: Photos.self)
    }
}

//MARK: - NetworkConnectionDelegate
extension PhotoListInteractor: NetworkConnectionDelegate {
    func dataReceived<T: Codable>(object: T) {
        let photos = object as! Photos
        presenter?.receivedData(data: photos)
    }
    
    func failedRequest(error: Errors) {
        presenter?.error(message: error.getErrorMessage())
    }
}
