//
//  InitViewController.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class InitViewController: UIViewController, InitViewProtocol {

	var presenter: InitPresenterProtocol?
    
    //MARK: - @IBOutlets
    @IBOutlet weak var containerView: GradientView!
    @IBOutlet weak var photoListView: UIView!
    @IBOutlet weak var albumListView: UIView!
    
    //MARK: - Properties
    var gradientView: GradientView!

    //MARK: - Life cycle
	override public func viewDidLoad() {
        super.viewDidLoad()
        
        setUpView()
    }
    
    override public func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        containerView.animateGradient()
    }
    
    //MARK: - Methods
    private func setUpView() {
        photoListView.setBorder(cornerRadius: 10)
        albumListView.setBorder(cornerRadius: 10)
    }
    
    //MARK: - Actions
    @IBAction private func goToPhotoList(_ sender: UIButton) {
        
    }
    
    @IBAction private func goToAlbumList(_ sender: UIButton) {
        let view = AlbumListRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
}
