//
//  InitInteractor.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class InitInteractor: InitInteractorProtocol {

    weak var presenter: InitPresenterProtocol?
}
