//
//  InitProtocols.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol InitWireframeProtocol: class {

}

//MARK: Presenter -
protocol InitPresenterProtocol: class {

}

//MARK: Interactor -
protocol InitInteractorProtocol: class {
    
    var presenter: InitPresenterProtocol?  { get set }
}

//MARK: View -
protocol InitViewProtocol: class {
    
    var presenter: InitPresenterProtocol?  { get set }
}
