//
//  PhotoListPresenter.swift
//  MediaMonksTest
//
//  Created Miguel Vicario on 06/01/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class PhotoListPresenter: PhotoListPresenterProtocol {

    weak private var view: PhotoListViewProtocol?
    var interactor: PhotoListInteractorProtocol?
    private let router: PhotoListWireframeProtocol

    init(interface: PhotoListViewProtocol, interactor: PhotoListInteractorProtocol?, router: PhotoListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - MakeRequest
    func makeRequest(method: Method) {
        interactor?.makeRequest(method: method)
    }
    
    //MARK: - ReceivedData
    func receivedData(data: Photos) {
        view?.receivedData(data: data)
    }
    
    //MARK: - Error
    func error(message: String) {
        view?.error(message: message)
    }
    
    //MARK: - GoToPhotoDetail
    func goToPhotoDetail(nav: UINavigationController?, photo: Photo?) {
        router.goToPhotoDetail(nav: nav, photo: photo)
    }
    
    //MARK: - GoBack
    func goBack(nav: UINavigationController?) {
        router.goBack(nav: nav)
    }

}
